<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'PGMB\\Vendor\\TypistTech\\WPAdminNotices\\' => array($vendorDir . '/typisttech/wp-admin-notices/src'),
    'PGMB\\Vendor\\Rarst\\WordPress\\DateTime\\' => array($vendorDir . '/rarst/wpdatetime/src'),
    'PGMB\\Vendor\\Mustache\\' => array($vendorDir . '/mustache/mustache/src'),
    'PGMB\\Vendor\\Html2Text\\' => array($vendorDir . '/html2text/html2text/src'),
    'PGMB\\Vendor\\Firebase\\JWT\\' => array($vendorDir . '/firebase/php-jwt/src'),
);
