<?php

// autoload_real.php @generated by Composer

class ComposerAutoloaderInitecb427ffd0d4d158d52f69b94e687765
{
    private static $loader;

    public static function loadClassLoader($class)
    {
        if ('PGMB\Vendor\Composer\Autoload\ClassLoader' === $class) {
            require __DIR__ . '/ClassLoader.php';
        }
    }

    /**
     * @return \PGMB\Vendor\Composer\Autoload\ClassLoader
     */
    public static function getLoader()
    {
        if (null !== self::$loader) {
            return self::$loader;
        }

        require __DIR__ . '/platform_check.php';

        spl_autoload_register(array('ComposerAutoloaderInitecb427ffd0d4d158d52f69b94e687765', 'loadClassLoader'), true, true);
        self::$loader = $loader = new \PGMB\Vendor\Composer\Autoload\ClassLoader(\dirname(__DIR__));
        spl_autoload_unregister(array('ComposerAutoloaderInitecb427ffd0d4d158d52f69b94e687765', 'loadClassLoader'));

        require __DIR__ . '/autoload_static.php';
        call_user_func(\PGMB\Vendor\Composer\Autoload\ComposerStaticInitecb427ffd0d4d158d52f69b94e687765::getInitializer($loader));

        $loader->setClassMapAuthoritative(true);
        $loader->register(true);

        return $loader;
    }
}
