<?php

// autoload_real.php @generated by Composer

class ComposerAutoloaderInit65d88090d2f3de52ea26034d39c193fc
{
    private static $loader;

    public static function loadClassLoader($class)
    {
        if ('PGMB\Vendor\Composer\Autoload\ClassLoader' === $class) {
            require __DIR__ . '/ClassLoader.php';
        }
    }

    /**
     * @return \PGMB\Vendor\Composer\Autoload\ClassLoader
     */
    public static function getLoader()
    {
        if (null !== self::$loader) {
            return self::$loader;
        }

        require __DIR__ . '/platform_check.php';

        spl_autoload_register(array('ComposerAutoloaderInit65d88090d2f3de52ea26034d39c193fc', 'loadClassLoader'), true, true);
        self::$loader = $loader = new \PGMB\Vendor\Composer\Autoload\ClassLoader(\dirname(__DIR__));
        spl_autoload_unregister(array('ComposerAutoloaderInit65d88090d2f3de52ea26034d39c193fc', 'loadClassLoader'));

        require __DIR__ . '/autoload_static.php';
        call_user_func(\PGMB\Vendor\Composer\Autoload\ComposerStaticInit65d88090d2f3de52ea26034d39c193fc::getInitializer($loader));

        $loader->setClassMapAuthoritative(true);
        $loader->register(true);

        return $loader;
    }
}
