<?php

// autoload_real.php @generated by Composer

class ComposerAutoloaderInitc4d462e8a68125a5f8373998ebb9da07
{
    private static $loader;

    public static function loadClassLoader($class)
    {
        if ('PGMB\Vendor\Composer\Autoload\ClassLoader' === $class) {
            require __DIR__ . '/ClassLoader.php';
        }
    }

    /**
     * @return \PGMB\Vendor\Composer\Autoload\ClassLoader
     */
    public static function getLoader()
    {
        if (null !== self::$loader) {
            return self::$loader;
        }

        require __DIR__ . '/platform_check.php';

        spl_autoload_register(array('ComposerAutoloaderInitc4d462e8a68125a5f8373998ebb9da07', 'loadClassLoader'), true, true);
        self::$loader = $loader = new \PGMB\Vendor\Composer\Autoload\ClassLoader(\dirname(__DIR__));
        spl_autoload_unregister(array('ComposerAutoloaderInitc4d462e8a68125a5f8373998ebb9da07', 'loadClassLoader'));

        require __DIR__ . '/autoload_static.php';
        call_user_func(\PGMB\Vendor\Composer\Autoload\ComposerStaticInitc4d462e8a68125a5f8373998ebb9da07::getInitializer($loader));

        $loader->setClassMapAuthoritative(true);
        $loader->register(true);

        return $loader;
    }
}
