<?php

// autoload_static.php @generated by Composer

namespace PGMB\Vendor\Composer\Autoload;

class ComposerStaticInit65d88090d2f3de52ea26034d39c193fc
{
    public static $prefixLengthsPsr4 = array (
        'P' =>
        array (
            'PGMB\\Vendor\\TypistTech\\WPAdminNotices\\' => 38,
            'PGMB\\Vendor\\Rarst\\WordPress\\DateTime\\' => 37,
            'PGMB\\Vendor\\Mustache\\' => 21,
            'PGMB\\Vendor\\Html2Text\\' => 22,
            'PGMB\\Vendor\\Firebase\\JWT\\' => 25,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'PGMB\\Vendor\\TypistTech\\WPAdminNotices\\' =>
        array (
            0 => __DIR__ . '/..' . '/typisttech/wp-admin-notices/src',
        ),
        'PGMB\\Vendor\\Rarst\\WordPress\\DateTime\\' =>
        array (
            0 => __DIR__ . '/..' . '/rarst/wpdatetime/src',
        ),
        'PGMB\\Vendor\\Mustache\\' =>
        array (
            0 => __DIR__ . '/..' . '/mustache/mustache/src',
        ),
        'PGMB\\Vendor\\Html2Text\\' =>
        array (
            0 => __DIR__ . '/..' . '/html2text/html2text/src',
        ),
        'PGMB\\Vendor\\Firebase\\JWT\\' =>
        array (
            0 => __DIR__ . '/..' . '/firebase/php-jwt/src',
        ),
    );

    public static $classMap = array (
        'PGMB\\Vendor\\Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
        'Mustache_Cache' => __DIR__ . '/..' . '/mustache/mustache/src/compat.php',
        'Mustache_Exception' => __DIR__ . '/..' . '/mustache/mustache/src/compat.php',
        'Mustache_Loader' => __DIR__ . '/..' . '/mustache/mustache/src/compat.php',
        'Mustache_Loader_MutableLoader' => __DIR__ . '/..' . '/mustache/mustache/src/compat.php',
        'Mustache_Logger' => __DIR__ . '/..' . '/mustache/mustache/src/compat.php',
        'Mustache_Source' => __DIR__ . '/..' . '/mustache/mustache/src/compat.php',
        'PGMB\\Vendor\\Firebase\\JWT\\BeforeValidException' => __DIR__ . '/..' . '/firebase/php-jwt/src/BeforeValidException.php',
        'PGMB\\Vendor\\Firebase\\JWT\\CachedKeySet' => __DIR__ . '/..' . '/firebase/php-jwt/src/CachedKeySet.php',
        'PGMB\\Vendor\\Firebase\\JWT\\ExpiredException' => __DIR__ . '/..' . '/firebase/php-jwt/src/ExpiredException.php',
        'PGMB\\Vendor\\Firebase\\JWT\\JWK' => __DIR__ . '/..' . '/firebase/php-jwt/src/JWK.php',
        'PGMB\\Vendor\\Firebase\\JWT\\JWT' => __DIR__ . '/..' . '/firebase/php-jwt/src/JWT.php',
        'PGMB\\Vendor\\Firebase\\JWT\\JWTExceptionWithPayloadInterface' => __DIR__ . '/..' . '/firebase/php-jwt/src/JWTExceptionWithPayloadInterface.php',
        'PGMB\\Vendor\\Firebase\\JWT\\Key' => __DIR__ . '/..' . '/firebase/php-jwt/src/Key.php',
        'PGMB\\Vendor\\Firebase\\JWT\\SignatureInvalidException' => __DIR__ . '/..' . '/firebase/php-jwt/src/SignatureInvalidException.php',
        'PGMB\\Vendor\\Html2Text\\Html2Text' => __DIR__ . '/..' . '/html2text/html2text/src/Html2Text.php',
        'PGMB\\Vendor\\Mustache\\Cache' => __DIR__ . '/..' . '/mustache/mustache/src/Cache.php',
        'PGMB\\Vendor\\Mustache\\Cache\\AbstractCache' => __DIR__ . '/..' . '/mustache/mustache/src/Cache/AbstractCache.php',
        'PGMB\\Vendor\\Mustache\\Cache\\FilesystemCache' => __DIR__ . '/..' . '/mustache/mustache/src/Cache/FilesystemCache.php',
        'PGMB\\Vendor\\Mustache\\Cache\\NoopCache' => __DIR__ . '/..' . '/mustache/mustache/src/Cache/NoopCache.php',
        'PGMB\\Vendor\\Mustache\\Compiler' => __DIR__ . '/..' . '/mustache/mustache/src/Compiler.php',
        'PGMB\\Vendor\\Mustache\\Context' => __DIR__ . '/..' . '/mustache/mustache/src/Context.php',
        'PGMB\\Vendor\\Mustache\\Engine' => __DIR__ . '/..' . '/mustache/mustache/src/Engine.php',
        'PGMB\\Vendor\\Mustache\\Exception' => __DIR__ . '/..' . '/mustache/mustache/src/Exception.php',
        'PGMB\\Vendor\\Mustache\\Exception\\InvalidArgumentException' => __DIR__ . '/..' . '/mustache/mustache/src/Exception/InvalidArgumentException.php',
        'PGMB\\Vendor\\Mustache\\Exception\\LogicException' => __DIR__ . '/..' . '/mustache/mustache/src/Exception/LogicException.php',
        'PGMB\\Vendor\\Mustache\\Exception\\RuntimeException' => __DIR__ . '/..' . '/mustache/mustache/src/Exception/RuntimeException.php',
        'PGMB\\Vendor\\Mustache\\Exception\\SyntaxException' => __DIR__ . '/..' . '/mustache/mustache/src/Exception/SyntaxException.php',
        'PGMB\\Vendor\\Mustache\\Exception\\UnknownFilterException' => __DIR__ . '/..' . '/mustache/mustache/src/Exception/UnknownFilterException.php',
        'PGMB\\Vendor\\Mustache\\Exception\\UnknownHelperException' => __DIR__ . '/..' . '/mustache/mustache/src/Exception/UnknownHelperException.php',
        'PGMB\\Vendor\\Mustache\\Exception\\UnknownTemplateException' => __DIR__ . '/..' . '/mustache/mustache/src/Exception/UnknownTemplateException.php',
        'PGMB\\Vendor\\Mustache\\HelperCollection' => __DIR__ . '/..' . '/mustache/mustache/src/HelperCollection.php',
        'PGMB\\Vendor\\Mustache\\LambdaHelper' => __DIR__ . '/..' . '/mustache/mustache/src/LambdaHelper.php',
        'PGMB\\Vendor\\Mustache\\Loader' => __DIR__ . '/..' . '/mustache/mustache/src/Loader.php',
        'PGMB\\Vendor\\Mustache\\Loader\\ArrayLoader' => __DIR__ . '/..' . '/mustache/mustache/src/Loader/ArrayLoader.php',
        'PGMB\\Vendor\\Mustache\\Loader\\CascadingLoader' => __DIR__ . '/..' . '/mustache/mustache/src/Loader/CascadingLoader.php',
        'PGMB\\Vendor\\Mustache\\Loader\\FilesystemLoader' => __DIR__ . '/..' . '/mustache/mustache/src/Loader/FilesystemLoader.php',
        'PGMB\\Vendor\\Mustache\\Loader\\InlineLoader' => __DIR__ . '/..' . '/mustache/mustache/src/Loader/InlineLoader.php',
        'PGMB\\Vendor\\Mustache\\Loader\\MutableLoader' => __DIR__ . '/..' . '/mustache/mustache/src/Loader/MutableLoader.php',
        'PGMB\\Vendor\\Mustache\\Loader\\ProductionFilesystemLoader' => __DIR__ . '/..' . '/mustache/mustache/src/Loader/ProductionFilesystemLoader.php',
        'PGMB\\Vendor\\Mustache\\Loader\\StringLoader' => __DIR__ . '/..' . '/mustache/mustache/src/Loader/StringLoader.php',
        'PGMB\\Vendor\\Mustache\\Logger' => __DIR__ . '/..' . '/mustache/mustache/src/Logger.php',
        'PGMB\\Vendor\\Mustache\\Logger\\AbstractLogger' => __DIR__ . '/..' . '/mustache/mustache/src/Logger/AbstractLogger.php',
        'PGMB\\Vendor\\Mustache\\Logger\\StreamLogger' => __DIR__ . '/..' . '/mustache/mustache/src/Logger/StreamLogger.php',
        'PGMB\\Vendor\\Mustache\\Parser' => __DIR__ . '/..' . '/mustache/mustache/src/Parser.php',
        'PGMB\\Vendor\\Mustache\\RenderedString' => __DIR__ . '/..' . '/mustache/mustache/src/RenderedString.php',
        'PGMB\\Vendor\\Mustache\\Source' => __DIR__ . '/..' . '/mustache/mustache/src/Source.php',
        'PGMB\\Vendor\\Mustache\\Source\\FilesystemSource' => __DIR__ . '/..' . '/mustache/mustache/src/Source/FilesystemSource.php',
        'PGMB\\Vendor\\Mustache\\Template' => __DIR__ . '/..' . '/mustache/mustache/src/Template.php',
        'PGMB\\Vendor\\Mustache\\Tokenizer' => __DIR__ . '/..' . '/mustache/mustache/src/Tokenizer.php',
        'PGMB\\Vendor\\Rarst\\WordPress\\DateTime\\WpDateTime' => __DIR__ . '/..' . '/rarst/wpdatetime/src/WpDateTime.php',
        'PGMB\\Vendor\\Rarst\\WordPress\\DateTime\\WpDateTimeImmutable' => __DIR__ . '/..' . '/rarst/wpdatetime/src/WpDateTimeImmutable.php',
        'PGMB\\Vendor\\Rarst\\WordPress\\DateTime\\WpDateTimeInterface' => __DIR__ . '/..' . '/rarst/wpdatetime/src/WpDateTimeInterface.php',
        'PGMB\\Vendor\\Rarst\\WordPress\\DateTime\\WpDateTimeTrait' => __DIR__ . '/..' . '/rarst/wpdatetime/src/WpDateTimeTrait.php',
        'PGMB\\Vendor\\Rarst\\WordPress\\DateTime\\WpDateTimeZone' => __DIR__ . '/..' . '/rarst/wpdatetime/src/WpDateTimeZone.php',
        'PGMB\\Vendor\\TypistTech\\WPAdminNotices\\AbstractNotice' => __DIR__ . '/..' . '/typisttech/wp-admin-notices/src/AbstractNotice.php',
        'PGMB\\Vendor\\TypistTech\\WPAdminNotices\\Factory' => __DIR__ . '/..' . '/typisttech/wp-admin-notices/src/Factory.php',
        'PGMB\\Vendor\\TypistTech\\WPAdminNotices\\Notice' => __DIR__ . '/..' . '/typisttech/wp-admin-notices/src/Notice.php',
        'PGMB\\Vendor\\TypistTech\\WPAdminNotices\\NoticeInterface' => __DIR__ . '/..' . '/typisttech/wp-admin-notices/src/NoticeInterface.php',
        'PGMB\\Vendor\\TypistTech\\WPAdminNotices\\Notifier' => __DIR__ . '/..' . '/typisttech/wp-admin-notices/src/Notifier.php',
        'PGMB\\Vendor\\TypistTech\\WPAdminNotices\\StickyNotice' => __DIR__ . '/..' . '/typisttech/wp-admin-notices/src/StickyNotice.php',
        'PGMB\\Vendor\\TypistTech\\WPAdminNotices\\Store' => __DIR__ . '/..' . '/typisttech/wp-admin-notices/src/Store.php',
        'PGMB\\Vendor\\TypistTech\\WPAdminNotices\\StoreInterface' => __DIR__ . '/..' . '/typisttech/wp-admin-notices/src/StoreInterface.php',
        'PGMB_Vendor_Mustache_Cache_AbstractCache' => __DIR__ . '/..' . '/mustache/mustache/src/compat.php',
        'PGMB_Vendor_Mustache_Cache_FilesystemCache' => __DIR__ . '/..' . '/mustache/mustache/src/compat.php',
        'PGMB_Vendor_Mustache_Cache_NoopCache' => __DIR__ . '/..' . '/mustache/mustache/src/compat.php',
        'PGMB_Vendor_Mustache_Compiler' => __DIR__ . '/..' . '/mustache/mustache/src/compat.php',
        'PGMB_Vendor_Mustache_Context' => __DIR__ . '/..' . '/mustache/mustache/src/compat.php',
        'PGMB_Vendor_Mustache_Engine' => __DIR__ . '/..' . '/mustache/mustache/src/compat.php',
        'PGMB_Vendor_Mustache_Exception_InvalidArgumentException' => __DIR__ . '/..' . '/mustache/mustache/src/compat.php',
        'PGMB_Vendor_Mustache_Exception_LogicException' => __DIR__ . '/..' . '/mustache/mustache/src/compat.php',
        'PGMB_Vendor_Mustache_Exception_RuntimeException' => __DIR__ . '/..' . '/mustache/mustache/src/compat.php',
        'PGMB_Vendor_Mustache_Exception_SyntaxException' => __DIR__ . '/..' . '/mustache/mustache/src/compat.php',
        'PGMB_Vendor_Mustache_Exception_UnknownFilterException' => __DIR__ . '/..' . '/mustache/mustache/src/compat.php',
        'PGMB_Vendor_Mustache_Exception_UnknownHelperException' => __DIR__ . '/..' . '/mustache/mustache/src/compat.php',
        'PGMB_Vendor_Mustache_Exception_UnknownTemplateException' => __DIR__ . '/..' . '/mustache/mustache/src/compat.php',
        'PGMB_Vendor_Mustache_HelperCollection' => __DIR__ . '/..' . '/mustache/mustache/src/compat.php',
        'PGMB_Vendor_Mustache_LambdaHelper' => __DIR__ . '/..' . '/mustache/mustache/src/compat.php',
        'PGMB_Vendor_Mustache_Loader_ArrayLoader' => __DIR__ . '/..' . '/mustache/mustache/src/compat.php',
        'PGMB_Vendor_Mustache_Loader_CascadingLoader' => __DIR__ . '/..' . '/mustache/mustache/src/compat.php',
        'PGMB_Vendor_Mustache_Loader_FilesystemLoader' => __DIR__ . '/..' . '/mustache/mustache/src/compat.php',
        'PGMB_Vendor_Mustache_Loader_InlineLoader' => __DIR__ . '/..' . '/mustache/mustache/src/compat.php',
        'PGMB_Vendor_Mustache_Loader_ProductionFilesystemLoader' => __DIR__ . '/..' . '/mustache/mustache/src/compat.php',
        'PGMB_Vendor_Mustache_Loader_StringLoader' => __DIR__ . '/..' . '/mustache/mustache/src/compat.php',
        'PGMB_Vendor_Mustache_Logger_AbstractLogger' => __DIR__ . '/..' . '/mustache/mustache/src/compat.php',
        'PGMB_Vendor_Mustache_Logger_StreamLogger' => __DIR__ . '/..' . '/mustache/mustache/src/compat.php',
        'PGMB_Vendor_Mustache_Parser' => __DIR__ . '/..' . '/mustache/mustache/src/compat.php',
        'PGMB_Vendor_Mustache_Source_FilesystemSource' => __DIR__ . '/..' . '/mustache/mustache/src/compat.php',
        'PGMB_Vendor_Mustache_Template' => __DIR__ . '/..' . '/mustache/mustache/src/compat.php',
        'PGMB_Vendor_Mustache_Tokenizer' => __DIR__ . '/..' . '/mustache/mustache/src/compat.php',
        'PGMB_Vendor_WP_Async_Request' => __DIR__ . '/..' . '/deliciousbrains/wp-background-processing/classes/wp-async-request.php',
        'PGMB_Vendor_WP_Background_Process' => __DIR__ . '/..' . '/deliciousbrains/wp-background-processing/classes/wp-background-process.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit65d88090d2f3de52ea26034d39c193fc::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit65d88090d2f3de52ea26034d39c193fc::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit65d88090d2f3de52ea26034d39c193fc::$classMap;

        }, null, ClassLoader::class);
    }
}
